# Generated by Django 3.1.4 on 2021-01-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
